name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            echo "📦 Deteniendo contenedor existente (si hay)..."
            docker stop fedefix_app || true
            docker rm fedefix_app || true

            echo "📥 Bajando última imagen desde Docker Hub..."
            docker-compose pull

            echo "🚀 Levantando contenedor actualizado..."
            docker-compose up -d --force-recreate --remove-orphans

            echo "✅ Deploy completado."
